[package]
name = "scenario_1"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.44.1", features = ["lazy", "temporal", "describe", "json", "parquet", "dtype-datetime","is_between"] }